In [3]:
import torch
num_donors = 4
D = 2
Q = torch.eye(num_donors, D, dtype=torch.float64, requires_grad=True)  
print(Q) 


tensor([[1., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64, requires_grad=True)


In [4]:
print(Q.T@Q)

tensor([[1., 0.],
        [0., 1.]], dtype=torch.float64, grad_fn=<MmBackward0>)


In [51]:
torch.manual_seed(215)
import numpy as np
np.random.seed(42)


num_outcomes = 2
outcomes = torch.rand(num_outcomes, num_donors, dtype=torch.float64)
print(outcomes)
print("norm of outcomes:\n",torch.norm(outcomes))

from scipy.stats import ortho_group
Q = ortho_group.rvs(dim=4)
Q = torch.from_numpy(Q)
Q = Q[:,0:3]
print("Sliced Q:\n",Q)

print("Product:\n",outcomes@Q)
print("norm of transformed outcomes:\n",torch.norm(outcomes@Q))




print(Q[:,0:1].T@Q[:,0:1])

tensor([[0.2314, 0.6294, 0.7132, 0.2151],
        [0.0464, 0.4968, 0.8437, 0.5712]], dtype=torch.float64)
norm of outcomes:
 tensor(1.5138, dtype=torch.float64)
Sliced Q:
 tensor([[ 0.6519,  0.2767,  0.2415],
        [-0.3073, -0.3002,  0.8974],
        [-0.6162, -0.0278, -0.3018],
        [ 0.3176, -0.9124, -0.2129]], dtype=torch.float64)
Product:
 tensor([[-0.4137, -0.3410,  0.3596],
        [-0.4609, -0.6809,  0.0808]], dtype=torch.float64)
norm of transformed outcomes:
 tensor(1.0485, dtype=torch.float64)
tensor([[1.0000]], dtype=torch.float64)
